[package]
name = "cc-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
env_logger = "0.11.7"
log = "0.4.27"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
